version: '3.8'

services:
  laravel:
    build:
      dockerfile: Dockerfile
    tty: true
    
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-debug}'
      XDEBUG_CONFIG: '${DEBUG_CONFIG:-client_host=host.docker.internal}'

    volumes:
      - '../apps:/var/www/html'
    
    networks:
    - devnet

networks:
    devnet:
        driver: bridge